clf;
n = -1:1;
x = [1 3 -2];
x_flip = x($:-1:1); 
xe = (x + x_flip)/2; 
subplot(3,1,1); 
xlabel("n"); 
ylabel("xe"); 
title("signal of x even"); 
plot2d3(n,xe); 
xo = (x - x_flip)/2; 
subplot(3,1,2); 
xlabel("n"); 
ylabel("xo"); 
title("signal of x odd"); 
plot2d3(n,xo); 
xn = xe + xo; 
subplot(3,1,3); 
xlabel("n"); 
ylabel("xn"); 
title("signal of x(n)"); 
plot2d3(n,xn);
